export const Strings = {
  // Main page
  PageTitle: 'UI Test Automation Playground',
  Title: 'UI Test Automation Playground',
  DynamicId: 'Dynamic ID',
  ClassAttribute: 'Class Attribute',
  HiddenLayers: 'Hidden Layers',
  LoadDelay: 'Load Delay',
  AjaxData: 'AJAX Data',
  ClientSideDelay: 'Client Side Delay',
  Click: 'Click',
  TextInput: 'Text Input',
  Scrollbars: 'Scrollbars',
  DynamicTable: 'Dynamic Table',
  VerifyText: 'Verify Text',
  ProgressBar: 'Progress Bar',
  Visibility: 'Visibility',
  SampleApp: 'Sample App',
  MouseOver: 'Mouse Over',
  NonBreakingSpace: 'Non-Breaking Space',
  OverlappedElement: 'Overlapped Element',
  ShadowDom: 'Shadow DOM',
  Alerts: 'Alerts',
  FileUpload: 'File Upload',
  AnimatedButton: 'Animated Button',
  DisabledInput: 'Disabled Input',
  AutoWait: 'Auto Wait',

  // SampleApp page
  WrongPasswordMessage: 'Invalid username/password',
  WelcomeUserMessage: 'Welcome,',

  // Upload page
  MessageOfUpload: '1 file(s) selected',
} as const;

export const Links: string[] = [
  Strings.DynamicId,
  Strings.ClassAttribute,
  Strings.HiddenLayers,
  Strings.AjaxData,
  Strings.ClientSideDelay,
  Strings.Click,
  Strings.TextInput,
  Strings.Scrollbars,
  Strings.DynamicTable,
  Strings.VerifyText,
  Strings.ProgressBar,
  Strings.Visibility,
  Strings.SampleApp,
  Strings.MouseOver,
  Strings.NonBreakingSpace,
  Strings.OverlappedElement,
  Strings.ShadowDom,
  Strings.Alerts,
  Strings.FileUpload,
  Strings.AnimatedButton,
  Strings.DisabledInput,
  Strings.AutoWait,
];
